# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDE5MTI4MTI3MzQyNTkxYjc0NDhhMDJlMjBiNTRkYTljMWM0M2IxMzdhNzVmYzZiMjU0YTdhMzRjYzdmNTVkNjgwOGViYjFmMzQ2NGU2ZGM0YjhjMDk5MTY3NTczN2JhZjI4YTg1NWQ1NjYwMmQwYzY5NzUwZmY4YjZlNTNhMjU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
